# Site
name: "The Mommy Geek"
author: 'The Mommy Geek'
description: "The Mommy Geek"
meta_description: "blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 
disqus: 

# Site Links
facebook:
linkedin:
twitter: MommyGeek
stackoverflow:

# Authors
authors:
  susana:
    name: 'Susana'
    display_name: 'Susana'
    gravatar:
    email:
    web: https://www.themommygeek.com
    twitter: https://twitter.com/MommyGeek
    description: "Just another geek in a geeky world"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive
  permalinks:
    category: /categories/:name/
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge